In [1]:
import utils
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import torch
import torch.nn as nn
from torch.utils.tensorboard import SummaryWriter

In [2]:
tr_df = pd.read_csv('data/adult.data', header=None)

In [3]:
columns = ["age", "workclass", "fnlwgt", "education", "education-num", 
           "marital-status", "occupation", "relationship", "race", "sex",
           "capital-gain","capital-loss","hours-per-week","native-country",
           "income"
          ]
index_c = {}
for i in range(len(columns)):
    index_c[i]=columns[i]
tr_df.rename(columns=index_c)
tr_df.columns = columns
tr_df.info()
tr_df
# categorize the data
# tr_df[1, 3,5,6,7,8,9,13,14] #= tr_df[1].astype('category')
# for i in [1, 3,5,6,7,8,9,13,14]:
#     tr_df[i] = tr_df[i].astype('category')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
income            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


age          workclass  fnlwgt    education  education-num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [4]:
tr_np = tr_df.to_numpy()

In [5]:
tr_df_i = tr_df.copy()


In [6]:
for i in columns:
    labelencoder= LabelEncoder()
    tr_df_i[i] = labelencoder.fit_transform(tr_df_i[i])

In [45]:
display(tr_df_i)
display(X_in_t.grad)

age  workclass  fnlwgt  education  education-num  marital-status  \
0       22          7    2671          9             12               4   
1       33          6    2926          9             12               2   
2       21          4   14086         11              8               0   
3       36          4   15336          1              6               2   
4       11          4   19355          9             12               2   
...    ...        ...     ...        ...            ...             ...   
32556   10          4   16528          7             11               2   
32557   23          4    8080         11              8               2   
32558   41          4    7883         11              8               6   
32559    5          4   12881         11              8               4   
32560   35          5   17825         11              8               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               1             1     4    1            25             0   
1               4             0     4    1             0             0   
2               6             1     4    1             0             0   
3               6             0     2    1             0             0   
4              10             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          13             5     4    0             0             0   
32557           7             0     4    1             0             0   
32558           1             4     4    0             0             0   
32559           1             3     4    1             0             0   
32560           4             5     4    0           108             0   

       hours-per-week  native-country  income  
0                  39              39       0  
1                  12              39       0  
2                  39              39       0  
3                  39              39       0  
4                  39               5       0  
...               ...             ...     ...  
32556              37              39       0  
32557              39              39       1  
32558              39              39       0  
32559              19              39       0  
32560              39              39       1  

[32561 rows x 15 columns]

tensor([ 0.7065, -0.3301,  0.1005,  0.1530,  1.3193, -0.1334, -0.0467, -1.0483,
         0.0188, -0.0555, -0.2192,  0.5753,  0.1569, -0.0211])

In [8]:
tr_df_i.describe()

age     workclass        fnlwgt     education  education-num  \
count  32561.000000  32561.000000  32561.000000  32561.000000   32561.000000   
mean      21.580326      3.868892  10498.892479     10.298210       9.080679   
std       13.635502      1.455960   6048.972814      3.870264       2.572720   
min        0.000000      0.000000      0.000000      0.000000       0.000000   
25%       11.000000      4.000000   5396.000000      9.000000       8.000000   
50%       20.000000      4.000000  10348.000000     11.000000       9.000000   
75%       31.000000      4.000000  15487.000000     12.000000      11.000000   
max       72.000000      8.000000  21647.000000     15.000000      15.000000   

       marital-status    occupation  relationship          race           sex  \
count    32561.000000  32561.000000  32561.000000  32561.000000  32561.000000   
mean         2.611836      6.572740      1.446362      3.665858      0.669205   
std          1.506222      4.228857      1.606771      0.848806      0.470506   
min          0.000000      0.000000      0.000000      0.000000      0.000000   
25%          2.000000      3.000000      0.000000      4.000000      0.000000   
50%          2.000000      7.000000      1.000000      4.000000      1.000000   
75%          4.000000     10.000000      3.000000      4.000000      1.000000   
max          6.000000     14.000000      5.000000      4.000000      1.000000   

       capital-gain  capital-loss  hours-per-week  native-country  \
count  32561.000000  32561.000000    32561.000000    32561.000000   
mean       6.501213      2.053285       39.377937       36.718866   
std       23.300287     10.056564       12.144006        7.823782   
min        0.000000      0.000000        0.000000        0.000000   
25%        0.000000      0.000000       39.000000       39.000000   
50%        0.000000      0.000000       39.000000       39.000000   
75%        0.000000      0.000000       44.000000       39.000000   
max      118.000000     91.000000       93.000000       41.000000   

             income  
count  32561.000000  
mean       0.240810  
std        0.427581  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [9]:
data_np = tr_df_i.to_numpy(dtype='float')

In [10]:
data_np.shape
X, y = data_np[:,:-1], data_np[:,-1]

In [11]:
scaler = MinMaxScaler()
X_tr = scaler.fit_transform(X)

In [12]:
X_tr.shape, y.shape

((32561, 14), (32561,))

In [13]:
model = nn.Sequential(
    nn.Linear(14,6000),
    nn.ReLU(),
    nn.Linear(6000,6400),
    nn.ReLU(),
    nn.Linear(6400,200),
    nn.ReLU(),
    nn.Linear(200, 2)
)
criterion = nn.CrossEntropyLoss(reduction='mean')
batch_size = 64
# optimizer = torch.optim.Adam(model.parameters(), lr=5e-2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.005, momentum=0.8)
epochs = 10

In [14]:
## split to train and val
X_val, y_val = X_tr[-500:, :], y[-500:]
X_tr, y=X_tr[:-500, :], y[:-500]
N, D = X_tr.shape
print(N, D)

32061 14


In [15]:
epochs=20
writer = SummaryWriter(flush_secs=10)
loss_history=[]
for e in range(epochs):
    for i in range(0, N, batch_size):
        optimizer.zero_grad()
        X_batch = torch.as_tensor(X_tr[i:i+batch_size,:].reshape((-1,D)), dtype=torch.float)
        y_batch = torch.as_tensor(y[i:i+batch_size], dtype=torch.long)
        loss=criterion(model(X_batch), y_batch)
        loss.backward()
        optimizer.step()
        if writer is not None:
                writer.add_scalar("Loss/Train", loss.item())
        if i%10 == 9:
            loss_history.append(loss.item())
        if (i/batch_size)%200 == 99:
            print("epoch %i: iteration %i/%i= %s" % (e+1, i, N, str(loss.detach().numpy())))
            print('Accuracy: ', torch.sum(torch.argmax(model(torch.as_tensor(X_val, dtype=torch.float)), axis=1) == torch.as_tensor(y_val, dtype=torch.int))/float(len(y_val)))
            
print('Final Accuracy: ', torch.sum(torch.argmax(model(torch.as_tensor(X_val, dtype=torch.float)), axis=1) == torch.as_tensor(y_val, dtype=torch.int))/float(len(y_val)))

epoch 1: iteration 6336/32061= 0.42438918
Accuracy:  tensor(0.7620)
epoch 1: iteration 19136/32061= 0.29972517
Accuracy:  tensor(0.8320)
epoch 1: iteration 31936/32061= 0.39070252
Accuracy:  tensor(0.8420)
epoch 2: iteration 6336/32061= 0.3479459
Accuracy:  tensor(0.8460)
epoch 2: iteration 19136/32061= 0.24434409
Accuracy:  tensor(0.8440)
epoch 2: iteration 31936/32061= 0.36672235
Accuracy:  tensor(0.8440)
epoch 3: iteration 6336/32061= 0.34292328
Accuracy:  tensor(0.8420)
epoch 3: iteration 19136/32061= 0.2597386
Accuracy:  tensor(0.8440)
epoch 3: iteration 31936/32061= 0.36476782
Accuracy:  tensor(0.8440)
epoch 4: iteration 6336/32061= 0.33256343
Accuracy:  tensor(0.8420)
epoch 4: iteration 19136/32061= 0.2522366
Accuracy:  tensor(0.8360)
epoch 4: iteration 31936/32061= 0.3604757
Accuracy:  tensor(0.8420)
epoch 5: iteration 6336/32061= 0.32168555
Accuracy:  tensor(0.8380)
epoch 5: iteration 19136/32061= 0.23930027
Accuracy:  tensor(0.8380)
epoch 5: iteration 31936/32061= 0.3535328
A

X_val_t = torch.as_tensor(X_val)
X_val_t.requires_grad = True
test_crit = nn.

In [17]:
X_i = X_tr[10,:]
display(X_i)

array([0.27777778, 0.5       , 0.80981198, 1.        , 0.6       ,
       0.33333333, 0.28571429, 0.        , 0.5       , 1.        ,
       0.        , 0.        , 0.8172043 , 0.95121951])

In [46]:
X_in_t = torch.as_tensor(X_tr[100,:], dtype=torch.float)
X_in_t.requires_grad = True
X_res_i = model(X_in_t)
display(X_res_i)
display(y[10])

tensor([-0.1675,  0.2485], grad_fn=<AddBackward0>)

1.0

In [47]:
res = nn.Sigmoid()(X_res_i)

In [48]:
res

tensor([0.4582, 0.5618], grad_fn=<SigmoidBackward>)

In [49]:
loss = nn.L1Loss(reduction='sum')(torch.tensor([1, 0]),  res)

In [50]:
loss.backward()

In [51]:
display(X_in_t.grad)

tensor([-0.8581, -0.1553,  0.0176,  0.2510,  1.2143,  0.1930,  0.0585, -0.9273,
         0.0537,  0.1163, -0.3861,  0.5234,  0.7713, -0.0580])